pipeline {
    agent any

    stages {
        stage("Clean up") {
            steps {
                deleteDir()
            }
        }

        stage("Build App") {
            steps {
                dir("gosample") {
                    sh '''
                        export GOROOT=/usr/local/go
                        export GOPATH=$HOME/go
                        export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
                        export CGO_ENABLED=1
                        export GOARCH=arm64
                        export CC=aarch64-linux-gnu-gcc

                        go mod init go.naous.net/api || true
                        go mod tidy
                        go build -o api
                        echo "Build completed!!!"
                    '''
                }
            }
        }

        stage("Run") {
            steps {
                dir("gosample") {
                    sh './api & sleep 3'
                }
            }
        }

        stage("Test") {
            steps {
                sh 'curl -s http://localhost:1337/events || echo "App is not responding."'
            }
        }
    }
}
